/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author IlyésBorbála(SZF_202
 */
public class GuiLampaNezet extends javax.swing.JFrame {

    private ActionListener kilepesListener;

    public GuiLampaNezet() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                if (kilepesListener != null) {
                    kilepesListener.actionPerformed(null);
                }
            }
        });
    }

    private void kilepes_Megerosit() {
        int valasz = JOptionPane.showConfirmDialog(
                this,
                "Biztos ki szeretnél lépni?",
                "Megerősítés",
                JOptionPane.YES_NO_OPTION
        );

        if (valasz == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    public void addKilepesListener(ActionListener listener) {
        this.kilepesListener = listener;
        mnuiKilepes.addActionListener(listener);
    }

    public void addLampButtonListener(int index, ActionListener listener) {
        getLampButton(index).addActionListener(listener);
    }

    private JButton getLampButton(int index) {
        switch (index) {
            case 0:
                return btnLampa1;
            case 1:
                return btnLampa2;
            case 2:
                return btnLampa3;
            case 3:
                return btnLampa4;
            case 4:
                return btnLampa5;
            case 5:
                return btnLampa6;
            case 6:
                return btnLampa7;
            case 7:
                return btnLampa8;
            case 8:
                return btnLampa9;
            default:
                return null;
        }
    }

    public void setMessage(String msg) {
        txtfKiiras.setText(msg);
    }

    public void setLampColor(int index, Color color) {
        JButton lamp = getLampButton(index);
        if (lamp != null) {
            lamp.setBackground(color);
        }
    }

    public void addUjJatekListener(ActionListener listener) {
        btnUjJatek.addActionListener(listener);
    }

    public void addUjJatekMenuListener(ActionListener listener) {
        mnuiUjJatek.addActionListener(listener);
    }

    public void addFajlbaMentListener(ActionListener listener) {
        mnuiFajlbaMent.addActionListener(listener);
    }

    public void addBetoltFajlbolListener(ActionListener listener) {
        mnuiBetoltFajlbol.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUjJatek = new javax.swing.JButton();
        txtfKiiras = new javax.swing.JTextField();
        pnlLampak = new javax.swing.JPanel();
        btnLampa1 = new javax.swing.JButton();
        btnLampa2 = new javax.swing.JButton();
        btnLampa3 = new javax.swing.JButton();
        btnLampa6 = new javax.swing.JButton();
        btnLampa5 = new javax.swing.JButton();
        btnLampa4 = new javax.swing.JButton();
        btnLampa7 = new javax.swing.JButton();
        btnLampa8 = new javax.swing.JButton();
        btnLampa9 = new javax.swing.JButton();
        lblCim = new javax.swing.JLabel();
        mnbMenu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuiFajlbaMent = new javax.swing.JMenuItem();
        mnuiBetoltFajlbol = new javax.swing.JMenuItem();
        mnuiUjJatek = new javax.swing.JMenuItem();
        mnuiKilepes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Light On Játék- Ilyés Bori");

        btnUjJatek.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnUjJatek.setText("Új Játék");

        txtfKiiras.setText("Játék célja: Kapcsold le az összes lámpát!");
        txtfKiiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfKiirasActionPerformed(evt);
            }
        });

        btnLampa1.setBackground(new java.awt.Color(0, 51, 204));
        btnLampa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLampa1ActionPerformed(evt);
            }
        });

        btnLampa2.setBackground(new java.awt.Color(0, 51, 204));
        btnLampa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLampa2ActionPerformed(evt);
            }
        });

        btnLampa3.setBackground(new java.awt.Color(0, 51, 204));
        btnLampa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLampa3ActionPerformed(evt);
            }
        });

        btnLampa6.setBackground(new java.awt.Color(0, 51, 204));
        btnLampa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLampa6ActionPerformed(evt);
            }
        });

        btnLampa5.setBackground(new java.awt.Color(0, 51, 204));
        btnLampa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLampa5ActionPerformed(evt);
            }
        });

        btnLampa4.setBackground(new java.awt.Color(0, 51, 204));
        btnLampa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLampa4ActionPerformed(evt);
            }
        });

        btnLampa7.setBackground(new java.awt.Color(0, 51, 204));
        btnLampa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLampa7ActionPerformed(evt);
            }
        });

        btnLampa8.setBackground(new java.awt.Color(0, 51, 204));
        btnLampa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLampa8ActionPerformed(evt);
            }
        });

        btnLampa9.setBackground(new java.awt.Color(0, 51, 204));
        btnLampa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLampa9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLampakLayout = new javax.swing.GroupLayout(pnlLampak);
        pnlLampak.setLayout(pnlLampakLayout);
        pnlLampakLayout.setHorizontalGroup(
            pnlLampakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLampakLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnlLampakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlLampakLayout.createSequentialGroup()
                        .addComponent(btnLampa7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLampa8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLampa9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLampakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLampakLayout.createSequentialGroup()
                            .addComponent(btnLampa4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnLampa5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnLampa6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlLampakLayout.createSequentialGroup()
                            .addComponent(btnLampa1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnLampa2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnLampa3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        pnlLampakLayout.setVerticalGroup(
            pnlLampakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLampakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLampakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLampa3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLampa2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLampa1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLampakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLampa4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLampa5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLampa6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLampakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLampa9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLampa8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLampa7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCim.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblCim.setText("Light On");

        mnuFile.setText("File");

        mnuiFajlbaMent.setText("Fájlba ment");
        mnuFile.add(mnuiFajlbaMent);

        mnuiBetoltFajlbol.setText("Belölt fajlból");
        mnuFile.add(mnuiBetoltFajlbol);

        mnuiUjJatek.setText("Új Játék");
        mnuFile.add(mnuiUjJatek);

        mnuiKilepes.setText("Kilépés");
        mnuFile.add(mnuiKilepes);

        mnbMenu.add(mnuFile);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblCim))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(pnlLampak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfKiiras, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUjJatek)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfKiiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLampak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnUjJatek)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfKiirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfKiirasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfKiirasActionPerformed

    private void btnLampa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLampa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLampa1ActionPerformed

    private void btnLampa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLampa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLampa2ActionPerformed

    private void btnLampa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLampa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLampa3ActionPerformed

    private void btnLampa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLampa6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLampa6ActionPerformed

    private void btnLampa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLampa5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLampa5ActionPerformed

    private void btnLampa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLampa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLampa4ActionPerformed

    private void btnLampa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLampa7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLampa7ActionPerformed

    private void btnLampa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLampa8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLampa8ActionPerformed

    private void btnLampa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLampa9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLampa9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLampa1;
    private javax.swing.JButton btnLampa2;
    private javax.swing.JButton btnLampa3;
    private javax.swing.JButton btnLampa4;
    private javax.swing.JButton btnLampa5;
    private javax.swing.JButton btnLampa6;
    private javax.swing.JButton btnLampa7;
    private javax.swing.JButton btnLampa8;
    private javax.swing.JButton btnLampa9;
    private javax.swing.JButton btnUjJatek;
    private javax.swing.JLabel lblCim;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuiBetoltFajlbol;
    private javax.swing.JMenuItem mnuiFajlbaMent;
    private javax.swing.JMenuItem mnuiKilepes;
    private javax.swing.JMenuItem mnuiUjJatek;
    private javax.swing.JPanel pnlLampak;
    private javax.swing.JTextField txtfKiiras;
    // End of variables declaration//GEN-END:variables
}
